version: "3.9"

services:
  database:
    image: mysql:8.0.33
    container_name: dst-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz@WSX3edc
      - MYSQL_DATABASE=dst
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - TZ=Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dst-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    depends_on:
      - database
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

volumes:
  mysql_data:
