"""add_log_method

Revision ID: 27555e666c45
Revises: 2e7528ec8ddf
Create Date: 2023-10-05 21:33:23.899423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27555e666c45'
down_revision = '2e7528ec8ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('method', sa.String(length=10), nullable=True))
        batch_op.alter_column('created_at',
                              existing_type=mysql.DATETIME(),
                              nullable=True,
                              existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                              existing_type=mysql.DATETIME(),
                              nullable=False,
                              existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('method')

    # ### end Alembic commands ###
