"""update_image_to_filepath

Revision ID: 2e7528ec8ddf
Revises: 402efe30e8fa
Create Date: 2023-10-05 20:09:07.129642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e7528ec8ddf'
down_revision = '402efe30e8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('path', sa.String(length=255), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('data', mysql.LONGBLOB(), nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
