"""improve_log

Revision ID: 363da2a97c6b
Revises: 27555e666c45
Create Date: 2023-10-13 14:54:25.845593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363da2a97c6b'
down_revision = '27555e666c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), [
                              'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), [
                              'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))

    # ### end Alembic commands ###
