"""remove_item_name

Revision ID: 402efe30e8fa
Revises: 5b83a5b5ebd6
Create Date: 2023-10-02 09:14:36.998354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '402efe30e8fa'
down_revision = '5b83a5b5ebd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
