"""add_erpFieldPermission_table

Revision ID: 48f38307cc0d
Revises: adde15489643
Create Date: 2025-07-12 07:33:29.764294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f38307cc0d'
down_revision = 'adde15489643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_field_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('erp_field_name', sa.String(length=255), nullable=False),
    sa.Column('is_limit_field', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_field_permission')
    # ### end Alembic commands ###
