"""add_series_sequence

Revision ID: 5b83a5b5ebd6
Revises: d6d97463cc3a
Create Date: 2023-09-13 16:49:25.539820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b83a5b5ebd6'
down_revision = 'd6d97463cc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('sequence', sa.Integer(), nullable=False, autoincrement=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
