"""add_limit_field

Revision ID: 6d72a1c258b5
Revises: 363da2a97c6b
Create Date: 2023-11-24 13:08:27.830342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d72a1c258b5'
down_revision = '363da2a97c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_limit_field', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('is_limit_field')

    # ### end Alembic commands ###
