"""add_item_is_deleted

Revision ID: adde15489643
Revises: a88a9d199562
Create Date: 2025-07-09 09:33:12.127623

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "adde15489643"
down_revision = "a88a9d199562"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_deleted", sa.Boolean(), server_default=sa.text("0"), nullable=False
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")
    # ### end Alembic commands ###
