"""empty message

Revision ID: aefac71470f6
Revises: 060f37772a26
Create Date: 2023-07-14 11:18:02.772951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aefac71470f6'
down_revision = '060f37772a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
