"""empty message

Revision ID: bb057f0e1a11
Revises: aefac71470f6
Create Date: 2023-07-14 16:11:05.979186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb057f0e1a11'
down_revision = 'aefac71470f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
