"""add_iserp_column

Revision ID: c057f21f3f72
Revises: 1cf391b63e7a
Create Date: 2025-07-12 14:57:47.463010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c057f21f3f72'
down_revision = '1cf391b63e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_erp', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('is_erp')
    # ### end Alembic commands ###
