"""add is_erp column

Revision ID: ceb17bf80564
Revises: fc546b043d50
Create Date: 2023-08-07 15:51:48.720692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceb17bf80564'
down_revision = 'fc546b043d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_erp', sa.Boolean(), default=0, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('is_erp')

    # ### end Alembic commands ###
