"""add_item_status

Revision ID: d585cfd0feb8
Revises: a88a9d199562
Create Date: 2025-07-08 15:24:45.331550

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d585cfd0feb8"
down_revision = "a88a9d199562"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.Boolean(), server_default=sa.text("1"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
