"""add_log

Revision ID: d6d97463cc3a
Revises: 1bc3a5460140
Create Date: 2023-08-25 14:49:06.989992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6d97463cc3a'
down_revision = '1bc3a5460140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('url', sa.Text(), nullable=True),
                    sa.Column('payload', mysql.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                    ), nullable=False, server_default=sa.func.now()),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    # ### end Alembic commands ###
