"""change_iserp_to_searcherp

Revision ID: 1cf391b63e7a
Revises: adde15489643
Create Date: 2025-07-12 14:50:21.862080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cf391b63e7a'
down_revision = 'adde15489643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.alter_column(
            'is_erp',
            new_column_name='search_erp',
            existing_type=sa.Boolean(),  # 必須指定現有欄位類型
            existing_nullable=False       # 必須指定現有的 nullable 狀態
        )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.alter_column(
            'search_erp',
            new_column_name='is_erp',
            existing_type=sa.Boolean(),
            existing_nullable=False
        )


    # ### end Alembic commands ###
