"""add_image_table

Revision ID: fc546b043d50
Revises: 96676b1b8ecd
Create Date: 2023-08-07 15:48:40.064346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc546b043d50'
down_revision = '96676b1b8ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('data', sa.LargeBinary(
                        length=(2**32)-1), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              nullable=False, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text(
                        'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
