name: Python Flask CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: 1qaz@WSX3edc
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-node@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -P 3306 -uroot -ppassword -e 'select 1'; do
            echo 'Waiting for MySQL...'
            sleep 1
          done

      - name: Run pytest
        env:
          MYSQL_HOSTNAME: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: 1qaz@WSX3edc
          MYSQL_DB: test
        run: |
          pip install pytest
          pytest
